# -*- coding: utf-8 -*-
"""task1_dat_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqNOwC2ZsRn2vJhv6Cj4cdGAQxjn8yHS
"""

import requests
import time
import os
import json
from datetime import datetime
from google.colab import files   # For downloading file

# -----------------------------
# CONFIGURATION
# -----------------------------
BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}

CATEGORIES = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

MAX_PER_CATEGORY = 25


# -----------------------------
# FETCH TOP STORY IDS
# -----------------------------
def get_top_story_ids():
    try:
        url = f"{BASE_URL}/topstories.json"
        response = requests.get(url, headers=HEADERS)
        response.raise_for_status()
        return response.json()[:500]
    except Exception as e:
        print("Error fetching top stories:", e)
        return []


# -----------------------------
# FETCH SINGLE STORY
# -----------------------------
def get_story(story_id):
    try:
        url = f"{BASE_URL}/item/{story_id}.json"
        response = requests.get(url, headers=HEADERS)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"Error fetching story {story_id}:", e)
        return None


# -----------------------------
# CATEGORIZE STORY
# -----------------------------
def categorize(title):
    if not title:
        return None

    title_lower = title.lower()

    for category, keywords in CATEGORIES.items():
        for keyword in keywords:
            if keyword in title_lower:
                return category

    return None


# -----------------------------
# MAIN FUNCTION
# -----------------------------
def main():
    top_ids = get_top_story_ids()

    collected = []
    category_count = {cat: 0 for cat in CATEGORIES}

    print("Fetching stories...")

    for story_id in top_ids:

        # Stop when all categories reach limit
        if all(count >= MAX_PER_CATEGORY for count in category_count.values()):
            break

        story = get_story(story_id)
        if not story:
            continue

        title = story.get("title", "")
        category = categorize(title)

        if not category:
            continue

        if category_count[category] >= MAX_PER_CATEGORY:
            continue

        # Extract required fields
        data = {
            "post_id": story.get("id"),
            "title": title,
            "category": category,
            "score": story.get("score", 0),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by", ""),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        collected.append(data)
        category_count[category] += 1

        print(f"[{category}] {title}")

        # Sleep after completing a category
        if category_count[category] % MAX_PER_CATEGORY == 0:
            print(f"Completed category: {category}")
            time.sleep(2)

    # -----------------------------
    # SAVE FILE
    # -----------------------------
    os.makedirs("data", exist_ok=True)

    filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(collected, f, indent=4)

    print(f"\nCollected {len(collected)} stories.")
    print(f"Saved to {filename}")

    # -----------------------------
    # DOWNLOAD TO YOUR PC
    # -----------------------------
    files.download(filename)


# -----------------------------
# RUN PROGRAM
# -----------------------------
if __name__ == "__main__":
    main()