# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqNOwC2ZsRn2vJhv6Cj4cdGAQxjn8yHS
"""

import pandas as pd          # For data handling
import numpy as np           # For numerical analysis
import os
from google.colab import files   # For download (Colab)

# -----------------------------
# STEP 1: LOAD CLEAN CSV
# -----------------------------

filename = "data/trends_clean.csv"

# Check if file exists
if not os.path.exists(filename):
    print("Error: trends_clean.csv not found. Run Task 2 first.")
else:
    # Load CSV into DataFrame
    df = pd.read_csv(filename)

    # Print shape (rows, columns)
    print(f"Loaded data: {df.shape}")

    # Print first 5 rows
    print("\nFirst 5 rows:")
    print(df.head())

    # -----------------------------
    # BASIC AVERAGES
    # -----------------------------
    avg_score = df["score"].mean()
    avg_comments = df["num_comments"].mean()

    print(f"\nAverage score   : {int(avg_score)}")
    print(f"Average comments: {int(avg_comments)}")


    # -----------------------------
    # STEP 2: NUMPY ANALYSIS
    # -----------------------------
    print("\n--- NumPy Stats ---")

    scores = df["score"].values   # Convert to NumPy array

    # Mean, Median, Std Dev
    print(f"Mean score   : {int(np.mean(scores))}")
    print(f"Median score : {int(np.median(scores))}")
    print(f"Std deviation: {int(np.std(scores))}")

    # Max and Min
    print(f"Max score    : {np.max(scores)}")
    print(f"Min score    : {np.min(scores)}")

    # Category with most stories
    category_counts = df["category"].value_counts()
    top_category = category_counts.idxmax()
    top_count = category_counts.max()

    print(f"\nMost stories in: {top_category} ({top_count} stories)")

    # Story with most comments
    max_comments_idx = df["num_comments"].idxmax()
    top_story_title = df.loc[max_comments_idx, "title"]
    top_story_comments = df.loc[max_comments_idx, "num_comments"]

    print(f"\nMost commented story: \"{top_story_title}\" — {top_story_comments} comments")


    # -----------------------------
    # STEP 3: ADD NEW COLUMNS
    # -----------------------------

    # Engagement = num_comments / (score + 1)
    df["engagement"] = df["num_comments"] / (df["score"] + 1)

    # is_popular = True if score > average score
    df["is_popular"] = df["score"] > avg_score


    # -----------------------------
    # STEP 4: SAVE NEW CSV
    # -----------------------------
    output_file = "data/trends_analysed.csv"

    df.to_csv(output_file, index=False)

    print(f"\nSaved to {output_file}")

    # -----------------------------
    # OPTIONAL: DOWNLOAD (COLAB)
    # -----------------------------
    files.download(output_file)