# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqNOwC2ZsRn2vJhv6Cj4cdGAQxjn8yHS
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# -----------------------------
# STEP 1: LOAD DATA
# -----------------------------

filename = "data/trends_analysed.csv"

# Check if file exists
if not os.path.exists(filename):
    print("Error: trends_analysed.csv not found. Run Task 3 first.")
else:
    df = pd.read_csv(filename)

    # Create outputs folder if not exists
    os.makedirs("outputs", exist_ok=True)

    # -----------------------------
    # CHART 1: TOP 10 STORIES BY SCORE
    # -----------------------------

    # Sort by score and take top 10
    top10 = df.sort_values(by="score", ascending=False).head(10)

    # Shorten long titles (max 50 characters)
    top10["short_title"] = top10["title"].apply(lambda x: x[:50] + "..." if len(x) > 50 else x)

    plt.figure()

    # Horizontal bar chart
    plt.barh(top10["short_title"], top10["score"])

    plt.xlabel("Score")
    plt.ylabel("Story Title")
    plt.title("Top 10 Stories by Score")

    plt.gca().invert_yaxis()  # Highest score at top

    # Save chart BEFORE showing
    plt.savefig("outputs/chart1_top_stories.png")

    plt.show()


    # -----------------------------
    # CHART 2: STORIES PER CATEGORY
    # -----------------------------

    category_counts = df["category"].value_counts()

    plt.figure()

    # Bar chart
    plt.bar(category_counts.index, category_counts.values)

    plt.xlabel("Category")
    plt.ylabel("Number of Stories")
    plt.title("Stories per Category")

    plt.xticks(rotation=30)

    plt.savefig("outputs/chart2_categories.png")

    plt.show()


    # -----------------------------
    # CHART 3: SCORE vs COMMENTS
    # -----------------------------

    plt.figure()

    # Separate popular and non-popular
    popular = df[df["is_popular"] == True]
    not_popular = df[df["is_popular"] == False]

    # Scatter plot
    plt.scatter(popular["score"], popular["num_comments"], label="Popular")
    plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

    plt.xlabel("Score")
    plt.ylabel("Number of Comments")
    plt.title("Score vs Comments")

    plt.legend()

    plt.savefig("outputs/chart3_scatter.png")

    plt.show()


    # -----------------------------
    # BONUS: DASHBOARD
    # -----------------------------

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # ---- Chart 1 (in dashboard) ----
    axes[0].barh(top10["short_title"], top10["score"])
    axes[0].set_title("Top 10 Stories")
    axes[0].set_xlabel("Score")
    axes[0].invert_yaxis()

    # ---- Chart 2 (in dashboard) ----
    axes[1].bar(category_counts.index, category_counts.values)
    axes[1].set_title("Categories")
    axes[1].set_xlabel("Category")
    axes[1].tick_params(axis='x', rotation=30)

    # ---- Chart 3 (in dashboard) ----
    axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
    axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
    axes[2].set_title("Score vs Comments")
    axes[2].set_xlabel("Score")
    axes[2].set_ylabel("Comments")
    axes[2].legend()

    # Overall title
    fig.suptitle("TrendPulse Dashboard")

    # Adjust layout
    plt.tight_layout()

    # Save dashboard
    plt.savefig("outputs/dashboard.png")

    plt.show()

    print("All charts saved in 'outputs/' folder")