# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqNOwC2ZsRn2vJhv6Cj4cdGAQxjn8yHS
"""

import pandas as pd
import os
from google.colab import files   # For downloading (if using Colab)

# -----------------------------
# STEP 1: FIND JSON FILE AUTOMATICALLY
# -----------------------------

# Check if data folder exists
if not os.path.exists("data"):
    print("Error: 'data' folder not found. Run Task 1 first.")
else:
    # Get all JSON files in data folder
    json_files = [f for f in os.listdir("data") if f.endswith(".json")]

    # If no JSON files found
    if not json_files:
        print("Error: No JSON file found in 'data' folder. Run Task 1 first.")
    else:
        # Pick the first JSON file
        filename = os.path.join("data", json_files[0])
        print(f"Using file: {filename}")

        # -----------------------------
        # STEP 2: LOAD JSON
        # -----------------------------
        df = pd.read_json(filename)
        print(f"Loaded {len(df)} stories from {filename}")

        # -----------------------------
        # STEP 3: CLEAN DATA
        # -----------------------------

        # 3.1 Remove duplicates
        df = df.drop_duplicates(subset="post_id")
        print(f"After removing duplicates: {len(df)}")

        # 3.2 Remove missing values
        df = df.dropna(subset=["post_id", "title", "score"])
        print(f"After removing nulls: {len(df)}")

        # 3.3 Fix data types
        df["score"] = df["score"].astype(int)
        df["num_comments"] = df["num_comments"].astype(int)

        # 3.4 Remove low-quality stories
        df = df[df["score"] >= 5]
        print(f"After removing low scores: {len(df)}")

        # 3.5 Strip whitespace in title
        df["title"] = df["title"].str.strip()

        # -----------------------------
        # STEP 4: SAVE CSV
        # -----------------------------
        output_file = "data/trends_clean.csv"
        df.to_csv(output_file, index=False)

        print(f"\nSaved {len(df)} rows to {output_file}")

        # -----------------------------
        # STEP 5: CATEGORY SUMMARY
        # -----------------------------
        print("\nStories per category:")
        print(df["category"].value_counts())

        # -----------------------------
        # STEP 6: DOWNLOAD FILE (COLAB)
        # -----------------------------
        files.download(output_file)